---
controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      update_rate: 1000
    multi_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

multi_joint_trajectory_controller:
  ros__parameters:
    joints:
      - front_sh
      - front_knee
      - front_ank
      - back_sh
      - back_knee
      - back_ank
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
