controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint1_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - front_sh
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_partial_joints_goal: true
      state_publish_rate: 50
      action_monitor_rate: 20